version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    container_name: jan_web
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION-22.0.0}
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD-admin}
    volumes:
      - ./keycloak-realm-config:/opt/keycloak/data/import
    ports:
      - "8080:8080"